version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=derbyops
      - DB_PORT=5432
      - JWT_SECRET=your-secret-key-here
      - JWT_EXPIRATION=24h
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - derbyops-network

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=derbyops
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - derbyops-network

volumes:
  postgres_data:

networks:
  derbyops-network:
    driver: bridge 