# Docker Compose for local development
version: '3.8'
services:
  api:
    build: ./api
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: derbyops
      POSTGRES_PASSWORD: derbyops
      POSTGRES_DB: derbyops
    ports:
      - "5432:5432"
