name: Branch Protection

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  branch-protection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Check branch name
        run: |
          if [[ ${{ github.ref }} != 'refs/heads/main' ]]; then
            echo "Error: Direct pushes to non-main branches are not allowed"
            exit 1
          fi
          
      - name: Check commit message
        run: |
          if ! echo "${{ github.event.head_commit.message }}" | grep -qE '^(feat|fix|docs|style|refactor|test|chore)(\(.+\))?: .+'; then
            echo "Error: Commit message does not follow conventional commits format"
            exit 1
          fi
          
      - name: Check PR title
        if: github.event_name == 'pull_request'
        run: |
          if ! echo "${{ github.event.pull_request.title }}" | grep -qE '^(feat|fix|docs|style|refactor|test|chore)(\(.+\))?: .+'; then
            echo "Error: PR title does not follow conventional commits format"
            exit 1
          fi 